"""
access_control.py
=================
Implements Role-Based Access Control (RBAC) and Multi-Factor Authentication (MFA).
Part of: CyberShield - Protecting Sensitive Data with Encryption and Access Control
Author: GPI Internship Project | Cloud Counselage
"""

import os
import hashlib
import hmac
import time
import random
import json
import re
from datetime import datetime
from typing import Optional


# ─────────────────────────────────────────────
#  Password Utilities
# ─────────────────────────────────────────────

def hash_password(password: str) -> str:
    """Hash password with SHA-256 + random salt (never store plain passwords)."""
    salt = os.urandom(32)
    key  = hashlib.pbkdf2_hmac('sha256', password.encode(), salt, 200_000)
    return salt.hex() + ":" + key.hex()

def verify_password(password: str, stored_hash: str) -> bool:
    """Verify a password against its stored hash."""
    try:
        salt_hex, key_hex = stored_hash.split(":")
        salt = bytes.fromhex(salt_hex)
        expected = hashlib.pbkdf2_hmac('sha256', password.encode(), salt, 200_000)
        return hmac.compare_digest(expected.hex(), key_hex)
    except Exception:
        return False


# ─────────────────────────────────────────────
#  Role Definitions
# ─────────────────────────────────────────────

ROLES = {
    "admin": {
        "description" : "Full system access",
        "permissions" : [
            "read_data", "write_data", "delete_data",
            "manage_users", "view_logs", "rotate_keys",
            "export_reports", "modify_policies"
        ]
    },
    "data_analyst": {
        "description" : "Read and analyze data; cannot delete or manage users",
        "permissions" : ["read_data", "export_reports", "view_logs"]
    },
    "employee": {
        "description" : "Standard employee access",
        "permissions" : ["read_data"]
    },
    "auditor": {
        "description" : "Read-only access to logs and reports",
        "permissions" : ["view_logs", "export_reports"]
    },
    "guest": {
        "description" : "Minimal access — public data only",
        "permissions" : []
    }
}


# ─────────────────────────────────────────────
#  TOTP-based MFA (RFC 6238 compliant)
# ─────────────────────────────────────────────

class MFAManager:
    """
    Time-based One-Time Password (TOTP) MFA system.
    Compatible with Google Authenticator / Authy.
    """

    TIME_STEP = 30   # seconds per TOTP window
    DIGITS    = 6

    def __init__(self):
        self.pending_codes: dict = {}   # user_id -> (code, expiry)

    def generate_secret(self) -> str:
        """Generate a user-specific TOTP secret (base32)."""
        import base64
        return base64.b32encode(os.urandom(20)).decode().rstrip("=")

    def generate_otp(self, secret: str = None) -> str:
        """
        Generate a 6-digit TOTP code.
        In production, this is generated by the authenticator app on the user's phone.
        Here we simulate it for demonstration.
        """
        if secret:
            import base64, struct
            # Real TOTP algorithm
            try:
                padded = secret + "=" * (-len(secret) % 8)
                key    = base64.b32decode(padded.upper())
                counter = int(time.time()) // self.TIME_STEP
                msg = struct.pack(">Q", counter)
                h   = hmac.new(key, msg, "sha1").digest()
                offset = h[-1] & 0x0F
                code = struct.unpack(">I", h[offset:offset+4])[0] & 0x7FFFFFFF
                return str(code % (10 ** self.DIGITS)).zfill(self.DIGITS)
            except Exception:
                pass
        # Fallback: random 6-digit OTP for simulation
        return str(random.randint(100000, 999999))

    def send_otp(self, user_id: str, secret: str) -> str:
        """Simulate sending OTP to user's registered device."""
        otp    = self.generate_otp(secret)
        expiry = time.time() + self.TIME_STEP
        self.pending_codes[user_id] = (otp, expiry)
        return otp   # In production, this is sent via SMS/email — NOT returned here

    def verify_otp(self, user_id: str, provided_code: str) -> bool:
        """Verify submitted OTP against the stored pending code."""
        if user_id not in self.pending_codes:
            return False
        code, expiry = self.pending_codes[user_id]
        if time.time() > expiry:
            del self.pending_codes[user_id]
            return False
        valid = hmac.compare_digest(code, provided_code.strip())
        if valid:
            del self.pending_codes[user_id]
        return valid


# ─────────────────────────────────────────────
#  User Store (simulated secure DB)
# ─────────────────────────────────────────────

class UserStore:
    """In-memory user store (replace with encrypted DB in production)."""

    def __init__(self):
        self._users: dict = {}

    def create_user(self, user_id: str, password: str, role: str,
                    email: str = "") -> dict:
        """Create a new user with hashed password and TOTP secret."""
        if user_id in self._users:
            raise ValueError(f"User '{user_id}' already exists.")
        if role not in ROLES:
            raise ValueError(f"Invalid role '{role}'. Choose: {list(ROLES)}")

        mfa     = MFAManager()
        secret  = mfa.generate_secret()

        self._users[user_id] = {
            "user_id"        : user_id,
            "password_hash"  : hash_password(password),
            "role"           : role,
            "email"          : email,
            "mfa_secret"     : secret,
            "mfa_enabled"    : True,
            "created_at"     : datetime.utcnow().isoformat(),
            "last_login"     : None,
            "failed_attempts": 0,
            "locked"         : False
        }
        return {"user_id": user_id, "role": role, "mfa_secret": secret}

    def get_user(self, user_id: str) -> Optional[dict]:
        return self._users.get(user_id)

    def lock_user(self, user_id: str):
        if user_id in self._users:
            self._users[user_id]["locked"] = True

    def record_failed_attempt(self, user_id: str):
        if user_id in self._users:
            self._users[user_id]["failed_attempts"] += 1
            if self._users[user_id]["failed_attempts"] >= 5:
                self.lock_user(user_id)

    def record_login(self, user_id: str):
        if user_id in self._users:
            self._users[user_id]["last_login"]      = datetime.utcnow().isoformat()
            self._users[user_id]["failed_attempts"] = 0

    def list_users(self) -> list:
        return [
            {k: v for k, v in u.items() if k not in ("password_hash", "mfa_secret")}
            for u in self._users.values()
        ]


# ─────────────────────────────────────────────
#  RBAC Engine
# ─────────────────────────────────────────────

class RBACEngine:
    """
    Role-Based Access Control engine.
    Checks permissions before any data operation.
    """

    def __init__(self):
        self.roles = ROLES

    def has_permission(self, role: str, permission: str) -> bool:
        """Check if a role has a specific permission."""
        return permission in self.roles.get(role, {}).get("permissions", [])

    def get_permissions(self, role: str) -> list:
        """Return all permissions for a given role."""
        return self.roles.get(role, {}).get("permissions", [])

    def enforce(self, role: str, permission: str, action_description: str = ""):
        """
        Enforce access control. Raises PermissionError if access is denied.
        Use before every sensitive operation.
        """
        if not self.has_permission(role, permission):
            raise PermissionError(
                f"ACCESS DENIED — Role '{role}' lacks '{permission}' permission."
                + (f" Attempted: {action_description}" if action_description else "")
            )

    def compare_roles(self) -> dict:
        """Return full permission matrix for all roles."""
        all_perms = sorted({p for r in self.roles.values() for p in r["permissions"]})
        matrix    = {}
        for role, data in self.roles.items():
            matrix[role] = {p: (p in data["permissions"]) for p in all_perms}
        return matrix


# ─────────────────────────────────────────────
#  Authentication Manager (ties it all together)
# ─────────────────────────────────────────────

class AuthManager:
    """
    Full authentication flow:
      1. Validate credentials (password check)
      2. Require MFA (TOTP)
      3. Issue session token
      4. RBAC enforcement on every action
    """

    SESSION_DURATION = 3600   # 1 hour

    def __init__(self, user_store: UserStore):
        self.store    = user_store
        self.mfa      = MFAManager()
        self.rbac     = RBACEngine()
        self.sessions : dict = {}   # session_token -> {user_id, role, expires_at}

    def authenticate(self, user_id: str, password: str) -> dict:
        """Step 1: Validate password, return MFA challenge."""
        user = self.store.get_user(user_id)
        if not user:
            raise ValueError("Authentication failed: User not found.")
        if user["locked"]:
            raise PermissionError("Account locked due to multiple failed login attempts.")

        if not verify_password(password, user["password_hash"]):
            self.store.record_failed_attempt(user_id)
            raise ValueError("Authentication failed: Invalid password.")

        # Send MFA challenge
        otp = self.mfa.send_otp(user_id, user["mfa_secret"])
        return {"status": "mfa_required", "otp_hint": otp}   # In prod, otp is NOT returned

    def verify_mfa_and_login(self, user_id: str, otp_code: str) -> str:
        """Step 2: Verify OTP, issue session token."""
        if not self.mfa.verify_otp(user_id, otp_code):
            raise ValueError("MFA verification failed: Invalid or expired OTP.")

        user  = self.store.get_user(user_id)
        token = hashlib.sha256(os.urandom(32)).hexdigest()
        self.sessions[token] = {
            "user_id"   : user_id,
            "role"      : user["role"],
            "expires_at": time.time() + self.SESSION_DURATION
        }
        self.store.record_login(user_id)
        return token

    def get_session(self, token: str) -> Optional[dict]:
        """Retrieve and validate a session."""
        session = self.sessions.get(token)
        if not session:
            return None
        if time.time() > session["expires_at"]:
            del self.sessions[token]
            return None
        return session

    def logout(self, token: str):
        """Invalidate a session token."""
        self.sessions.pop(token, None)

    def check_permission(self, token: str, permission: str) -> bool:
        """Check if the session owner has a given permission."""
        session = self.get_session(token)
        if not session:
            raise PermissionError("Session expired or invalid. Please log in again.")
        return self.rbac.has_permission(session["role"], permission)
